name: GitGuardian Scan

on:
  pull_request:
    branches:
      - main
      - nonprod
  push:
    branches:
      - main
      - nonprod
permissions: write-all

jobs:
  scanning:
    name: GitGuardian scan
    # permissions:
    #   contents: write
    #   pull-requests: write
    #   checks: write
    #   actions: read
    #   id-token: write
    #   packages: write
    uses: reminder-bot-microservices/.github/.github/workflows/scan_leaks.yaml@main
    with:
      GITGUARDIAN_ACCESS_TOKEN: ${{ secrets.GITGUARDIAN_ACCESS_TOKEN }}
