name: GitGuardian Scan

on:
  pull_request:
    branches:
      - main
      - nonprod
  push:
    branches:
      - main
      - nonprod
      - fix-vulnerabilities-pipe
      # tempo
permissions: write-all

jobs:
  scanning:
    name: GitGuardian scan
    uses: reminder-bot-microservices/.github/.github/workflows/scan_leaks.yaml@main
    secrets: inherit
